<?php

include_once('voipcall.features.inc');

/**
 * Save voipcall nodes. 
 * 
 * @param 
 *  $details = array with the following optional values:
 *    'nid', the nid of the voipcall node to be updated
 *    'dest_number', the destination number for the phone call
 *    'caller_number', the caller id number
 *    'caller_name', the caller id name
 *    'call_status', the status of the call. Possile values: 'processing error',
 *                   'not called', 'calling', 'answered', 'no answer', 'busy',
 *                   'invalid number'
 *    'script_name', the name of the dialplan script to be run when call is answered
 *    'start_time', the start time of the call
 *    'end_time', the end time of the call
 *    'other' array of 'field' => 'value' for other optional node fields to be
 *        set, e.g. uid, sticky, moderate, promoted, title, etc.
 *  );
 * 
 * @return
 *  $node, the newly saved voipcall node.
 */
function voipcall_save($details) {

  if(is_object($details)){
    $details = (array)$details;
  }

  // if this is a new call node being created
  if(is_null($details['nid'])){

    $node = new stdClass();

    // set the node type
    $node->type = 'voipcall';

    // define a unique identifier for the call
    $node->field_voipcall_call_id[0]['value'] = uniqid();

    // all calls start as 'not called'
    $node->field_voipcall_status[0]['value'] = 'not called';
  }
  else {
    // load the node
    $node = node_load($details['nid']);
  }

  // update selected fields

  global $user;
  $node->uid = $user->uid;          // UID of content owner

  if(!is_null($details['dest_number'])) $node->title = check_plain($details['dest_number']);
  if(!is_null($details['dest_number'])) $node->field_voipcall_dest_number[0]['value'] = $details['dest_number'];
  if(!is_null($details['caller_number'])) $node->field_voipcall_caller_number[0]['value'] = $details['caller_number'];
  if(!is_null($details['caller_name'])) $node->field_voipcall_caller_name[0]['value'] = $details['caller_name'];
  if(!is_null($details['call_status'])) $node->field_voipcall_status[0]['value'] = $details['call_status'];
  if(!is_null($details['script_name'])) $node->field_voipcall_script_name[0]['value'] =  $details['script_name'];
  if(!is_null($details['start_time'])) $node->field_voipcall_start_time[0]['value'] = $details['start_time'];
  if(!is_null($details['end_time'])) $node->field_voipcall_end_time[0]['value'] = $details['end_time'];

  // set other optional node fields
  if(!is_null($details['other'])){
    foreach($details['other'] as $field => $value){
      $node->$field = $value;
    }
  }

  // save the node
  node_save($node);

dsm($node);
  return $node;
}
