<?php

/**
 * Helper to implementation of hook_content_default_fields().
 */
function _calllist_content_default_fields() {
  $fields = array();

  // Exported field: field_calllist_phone_numbers
  $fields[] = array(
    'field_name' => 'field_calllist_phone_numbers',
    'type_name' => 'calllist',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '1',
    'multiple' => '1',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => 5,
      'size' => '15',
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_calllist_phone_numbers][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Phone numbers',
      'weight' => '31',
      'description' => '',
      'type' => 'text_textfield',
      'module' => 'text',
    ),
  );

  // Translatables
  array(
    t('Phone numbers'),
  );

  return $fields;
}
