<?php
// $Id$

/**
 * @file
 * Adds support for sending and receiving VoIP requests to and from Twilio.
 */

//-----------------------------------------------------------------------------
// Include files
//-----------------------------------------------------------------------------
foreach (array('voiptwilio.inc') as $file) {
  require_once(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . $file);
}


//-----------------------------------------------------------------------------
// Public functions
//-----------------------------------------------------------------------------

/**
 * Implementation of hook_voip_server_info().
 */
function voiptwilio_voip_server_info() {
  return array(
    'twilio' => array(
      'name' => 'Twilio',
      'configure form' => 'voiptwilio_admin_form',
      'send' => 'voiptwilio_send',
    ),
  );
}

function voiptwilio_admin_form($configuration) {
  $form['voiptwilio_account_sid'] = array(
    '#type' => 'textfield',
    '#title' => t('Twilio Account SID'),
    '#description' => t("The account SID provided in your Twilio account dashboard."),
    '#default_value' => ($configuration['voiptwilio_account_sid']?$configuration['voiptwilio_account_sid']:''),
  );
  $form['voiptwilio_auth_token'] = array(
    '#type' => 'textfield',
    '#title' => t('Twilio Auth Token'),
    '#description' => t("The authorization token provided in your Twilio account dashboard."),
    '#default_value' => ($configuration['voiptwilio_auth_token']?$configuration['voiptwilio_auth_token']:''),
  );
  $form['voiptwilio_cid_number'] = array(
    '#type' => 'textfield',
    '#title' => t('Caller id number'),
    '#description' => t('Caller id number to be used in Voip Drupal calls. That number has to be registered in the "Phone Numbers" section of your Twilio account.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => ($configuration['voiptwilio_cid_name']?$configuration['voiptwilio_cid_number']:'1234567890'),
  );

  return $form;
}

/**
 * Validates the submission of the configuration form.
 */
function voiptwilio_admin_form_validate($form, &$form_state) {

  // Send a test request to validate the configuration of the Twilio server
  $values = $form_state['values'];
  $result = _voiptwilio_ping($values);

  if(voip_error()){
    form_set_error('', t('A Twilio-related error occurred: @error', array('@error' => voip_error_message())));
  }
}

/**
 * Callback for sending requests to Twilio
 */
function voiptwilio_send($request_id, $options) {
  $server = voip_servers('server', 'twilio');
  $config = $server['configuration'];
dsm("config is: " . print_r($config,true));
  $result =  voiptwilio_send_request($config, $request_id, $options);
  return $result;
}

/**
 * Sends a request to Twilio
 */
function voiptwilio_send_request($server_config, $request_id, $options) {
dsm("in send_request config is: " . print_r($server_config,true));


  switch($request_id) {
    default:
      // Invalid request id
      $response = FALSE;
      $error_message = "Invalid request id received: %request_id.";
      $variables = array('%request_id' => $request_id);
      watchdog('voiptwilio', $error_message, $variables, WATCHDOG_ERROR);
      voip_error("(voiptwilio) Invalid request id received: " . $request_id);
      break;

    case 'voip_dial_out': // dial the given call node
      // call node
      $call_node = (object)$options;
      $response = _voiptwilio_dial_out($server_config, $call_node);
      break;
  }

  return $response;
}

/*
* Implementation of hook_disable()
*/
function voiptwilio_disable() {
  cache_clear_all('services:methods', 'cache');
}

/*
* Implementation of hook_enable()
*/
function voiptwilio_enable() {
  cache_clear_all('services:methods', 'cache');
}

/*
* Implementation of hook_service()
*/
function voiptwilio_service() {
  $methods = array();

  $methods[] = array(
    '#method'   => 'voiptwilio.callHandler',
    '#callback' => 'voiptwilio_call_handler',
    //'#key'     => FALSE,
    //'#auth'     => FALSE,
    '#args'     => array(),
    '#return'   => 'string',
    '#help'     => t('Handles incoming calls from Twilio.')
  );

  return $methods;
}


/*
 * Process incoming calls from Twilio
 *
 * Note: This function only works via REST API
 */
function voiptwilio_call_handler() {

dsm('voiptwilio_call_handler is alive and happy!');
dsm($_REQUEST);
$msg = 'in voiptwilio_call_handler() with $_REQUEST: ' . print_r($_REQUEST, TRUE);
$vars = array();
watchdog('voiptwilio', $msg, $vars, WATCHDOG_INFO);


  // process input here

  // call voiptwilio_script_handler()

  // send response back to Twilio
  $response = '
    <?xml version="1.0" encoding="UTF-8" ?>  
      <Response> 
        <Say>Hello World</Say>
        <Play>http://api.twilio.com/Cowbell.mp3</Play>
      </Response> ';

  return $response;

}

