<?php 
/**
 * @file
 *  Install Call Blast module.
 */

/**
 * Implementation of hook_install().
 */
function call_blast_install() {
  drupal_install_schema('call_blast');
}

/**
 * Implementation of hook_uninstall().
 */
function call_blast_uninstall() {
  drupal_uninstall_schema('call_blast');
}

/**
 * Implementation of hook_schema().
 */
function call_blast_schema() {
  /**
   * callblast_voipcall table
   * 
   * This table keeps track of which voipcall nodes
   * belong to which callblast nodes. That is, 
   * which calls are part of which callblast. 
   */
  $schema['callblast_voipcall'] = array(
    'fields' => array(
      'callblast_nid' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'voipcall_nid' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
    ), 
    'primary key' => array('callblast_nid', 'voipcall_nid'),
    ),
  );

  return $schema;
}
