<?php

// $Id$

/**
 * @file
 * "Handles the call scripts associated with the Voip Drupal platform."
 */


foreach (array('voipscript.features.inc') as $file) {
  require_once($file);
}

/**
 * Implementation of hook_voipscript_load_script()
 */
function voipscript_voipscript_load_script($script_name) {
  $script = NULL;
  $param = array('type' => 'voipscript', 'title' => $script_name, 'status' => 1);
  $script_node = node_load($param);
  if($script_node) {
dsm($script_node, '$script_node');
    $script_code = $script_node->field_voipscript_code[0]['value'];
dsm($script_code, '$script_code');
    ob_start();
    if(eval("$script_code")===false) {
      ob_end_clean();
      watchdog('voipscript', 'PHP syntax error in script: @script', array('@script' => $script_code), WATCHDOG_ERROR);
      return;
    }
    ob_end_clean();
  }
  return $script;
}

/**
 * Implementation of hook_validate()
 */
function voipscript_validate($node, &$form) {
  $script_code = $node->field_voipscript_code[0]['value'];
dsm($script_code, '$script_code');
  ob_start();
  if(eval("$script_code")===false) {
    ob_end_clean();
    form_set_error('field_voipscript_code', 
        t('PHP syntax error in script: @script',
          array('@script' => $script_code)));
  }
  ob_end_clean();
}

