<?php
/**
 * @file Handles scripts associated with the Voip Drupal platform
 */ 

foreach (array('voipscript_weather.inc') as $file) {
  require_once(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . $file);
}

foreach (array('voipscript.features.inc') as $file) {
  require_once($file);
}

/**
 * Implementation of hook_voipscript_load_script()
 */
function voipscript_voipscript_load_script($script_name, $params=NULL) {
  $script = NULL;
  $param = array('type' => 'voipscript', 'title' => $script_name, 'status' => 1);
  $script_node = node_load($param);
  if($script_node) {
    $script_code = $script_node->field_voipscript_code[0]['value'];
    ob_start();
    if(eval("$script_code")===false) {
      ob_end_clean();
      watchdog('voipscript', 'PHP syntax error in script: @script', array('@script' => $script_code), WATCHDOG_ERROR);
      return;
    }
    ob_end_clean();
  }
  else {
    $script = _voipscript_load_sample_scripts($script_name);
  }
  return $script;
}

/**
 * Implementation of hook_validate()
 */
function voipscript_validate($node, &$form) {
// TODO: why this function is not called?
  $script_code = $node->field_voipscript_code[0]['value'];
dsm($script_code, '$script_code');
  ob_start();
  if(eval("$script_code")===false) {
    ob_end_clean();
    form_set_error('field_voipscript_code',
        t('PHP syntax error in script: @script',
          array('@script' => $script_code)));
  }
  ob_end_clean();
}



/*
 * Sample scripts that highlight Voip Drupal capabilities
 */
function _voipscript_load_sample_scripts($script_name) {
  if($script_name == 'voipscript_weather_report') {
    $script = _voipscript_get_weather_report();
  }
  
  if($script_name == 'voipscript_gosub_test_a') {
    $script = new VoipScript('voipscript_gosub_test_a');
    $script->addSay('script a');
    $script->addGosub('voipscript_gosub_test_b');
    $script->addSay('back in script a');
    $script->addSay('bye bye');
    $script->addHangup();
  }

  if($script_name == 'voipscript_gosub_test_b') {
    $script = new VoipScript('voipscript_gosub_test_b');
    $script->addSay('script b');
    $script->addReturn();
  }

  if($script_name == 'voipscript_dial_test') {
    $script = _voipscript_get_dial_test_script();
  }

  if($script_name == 'voipscript_record') {
    $script = _voipscript_get_record_script();
  }

  return $script;
}


function _voipscript_get_dial_test_script() {
    $script = new VoipScript('voipscript_test');

    $script->addLabel('start');
    $script->addSay("Welcome to the Voip Drupal platform!");

    $script->addLabel('get input');

    $text = "To connect with the system developers, press 1.  To hangup, press the pound key.";
    $url = ''; // 'http://demo.twilio.com/hellomonkey/monkey.mp3';
    $timeout = 5;
    $end_key = '';
    $num_digits = 1;
    $script->addGetInput($text, $url, $timeout, $end_key, $num_digits);
    $script->addSay('You pressed: %input_digits');
    $script->addSet('user_input', '%input_digits');
    $script->addSay('The variable \'user input\' is now set to %user_input');

    $script->addGotoIf('end call', "^%input_digits == '#'");

    $script->addGotoIf('no input received', "^%input_digits == " . VoipScript::NO_INPUT);

//TODO: ask caller to input a 10-digit number
    $script->addSay('Dialing...'); 
    $number = '1234567890';
    $script->addDial($number);
    $script->addGoto('start');

    $script->addLabel('no input received');
    $script->addSay('No input received. Please try again.');
    $script->addGoto('get input');

    $script->addLabel('end call');
    $script->addSay('Bye bye');
    $script->addHangup();

    return $script;
  }


function _voipscript_get_record_script() {
  $script = new VoipScript('voipscript_record');

  $script->addLabel('start');
  $script->addSay("Please record your message after the beep.  When done, press the pound key.");
  $timeout = 5;
  $end_key = '#';
  $max_length = 20;
  $script->addRecord($timeout, $end_key, $max_length);

  $script->addSay('You said ');
  $script->addPlay('%recording_url');

  $script->addLabel('accept menu');
  $text = "To accept this recording, press 1.  To record it once again, press 2. To hangup, press the pound key.";
  $url = '';
  $timeout = 5;
  $end_key = '';
  $num_digits = 1;
  $script->addGetInput($text, $url, $timeout, $end_key, $num_digits);

  $script->addGotoIf('accept recording', "^%input_digits == '1'");

  $script->addGotoIf('start', "^%input_digits == '2'");

  $script->addGotoIf('end call', "^%input_digits == '#'");

  $script->addSay('Invalid input received. Please try again.');
  $script->addGoto('accept menu');

  $script->addLabel('accept recording');
  $script->addSay('About to start processing the recorded file.');
  $script->addSet('callback_result',
    '^_voipscript_record_callback(%call_id, %recording_url, %recording_duration)');
  $script->addSay('The callback returned: %callback_result');
  $script->addGoto('end call');

  $script->addLabel('no input received');
  $script->addSay("No input received. Please try again.");
  $script->addGoto('start');

  $script->addLabel('end call');
  $script->addSay('Bye bye.');
  $script->addHangup();

  return $script;
}

/**
 * Callback function associated with the script voipscript_record.  It is called
 * whenever that script records a new entry from the user.
 */
function _voipscript_record_callback($call_id, $recording_url, $recording_duration=NULL) {
watchdog('voipscript', "in _voipscript_record_callback($call_id, $recording_url, $recording_duration)");

  return 'Success';
}


