<?php

include_once('calllist.features.inc');

/**
 * Implementation of hook_callblast_list().
 */
function calllist_callblast_list() {
  $lists = array();
  $result = db_query(db_rewrite_sql("SELECT nid, title FROM {node} WHERE type = 'calllist'"));
  while ($list = db_fetch_object($result)) {
    $id = 'calllist_' . $list->nid;
    $name = t($list->title);
    $lists[$id] = $name; 
  }
  
  return $lists;
}

/**
 * Implementation of hook_callblast_get_list().
 * 
 * todo Add documentation for params and ability to return list name.
 */
function calllist_callblast_get_list($list_id, $op = 'full list') {
  switch ($op) {
    // return call list
    case 'full list': 
      // Get nid from machine readable list name.
      // Machine list name should be "modulename_" concatenated with "id".
      // (calllist module uses the nid as the call list's uniques id.)
      $nid = substr($list_id, 9);
  
      // Get numbers for selected list
      $result = db_query("SELECT nid FROM {node} WHERE nid = %d", $nid);
      $node = node_load($nid);
      $list = array();
      foreach ($node->field_calllist_phone_numbers as $num) {
        $list[]['destination'] = $num['value'];
      } 
      return $list;
    break; 

    // return human readable list name
    case 'list name': 
      // Get nid from machine readable list name.
      // Machine list name should be "modulename_" concatenated with "id".
      // (calllist module uses the nid as the call list's uniques id.)
      $nid = substr($list_id, 9);
      // Get node title.  
      $list_name = db_result(db_query("SELECT title FROM {node} WHERE nid = %d", $nid));
      return $list_name;
    break;
  } 
}

// TODO WRITE A HOOK FOR GETTING THE HUMAN READABLE NAME OF THE LIST
