<?php

include_once('calllist.features.inc');

/**
 * Implementation of hook_callblast_list().
 */
function calllist_callblast_list() {
  $lists = array();
  $result = db_query("SELECT nid, title FROM {node} WHERE type = 'calllist'");
  while ($list = db_fetch_object($result)) {
    $id = 'calllist_' . $list->nid;
    $name = t($list->title);
    $lists[$id] = $name; 
  }
  
  return $lists;
}

/**
 * Implementation of hook_callblast_get_list().
 */
function calllist_callblast_get_list($list_name) {
  // Get ID from list name.
  // List name should be "modulename_" concatenated with "id".
  $nid = substr($list_name, 9);
  
  // Get numbers for selected list
  $result = db_query("SELECT nid FROM {node} WHERE nid = %d", $nid);
  $node = node_load($nid);
  $list = array();
  foreach ($node->field_calllist_phone_numbers as $num) {
    $list[]['destination'] = $num['value'];
  } 

  return $list;
}

// TODO WRITE A HOOK FOR GETTING THE HUMAN READABLE NAME OF THE LIST
