<?php
/**
 * @file voip_extension.constants.inc
 *  Constants provided by Voip Extension module.
 */

/**
 * Use these constants for "error codes" in error handling. 
 */
define('VOIPEXT_SUCCESS', 1);                     // It worked. No error.
define('VOIPEXT_EXTENSION_DOES_NOT_EXIST', -7);   // The requested voip phone extension does not exist.
define('VOIPEXT_PROCESSING_FAILURE', -1);         // voipext was failed to process request.
