<?
/**
 * @file test VOIP hooks.
 */ 

/**
 * Implementation of hook_get_script().
 */
function voip_test_voip_get_script($script_name, $options) {
  $response = NULL;
  switch($script_name) {
    case 'test_failure':
      $response = FALSE;
      voip_error('(voip_test.module) test failure, as expected');
      break;
    case 'hello_world':
      $response = "<voip_script name='hello_world'><action name='say><text>Hello, world!</text></action></voip_script>";
      break;
  }

  return $response;
}

/**
 * Implementation of hook_voip_process_request().
 */
function voip_test_voip_process_request($request_id, $options) {
  $response = NULL;

  switch($request_id) {
    case 'voip_get_script':
      if ($options['script name']  == 'hello world') {
      $response['$request_id'] = $request_id . "\n";
      $response['$options'] = $options;
      $response['result'] = "<voip_script name='hello_world'><action name='say><text>Hello, world!</text></action></voip_script>";
      break;
      }
  }

  return $response;
}

