<?php
/**
 * @file test VOIP hooks.
 */ 

/**
 * Implementation of hook_voip_process_request().
 */
function voip_test_voip_process_request($request_id, $options) {
  $response = NULL;

  switch($request_id) {
    case 'voip_get_script':
      switch ($options['script_name']){
        case 'hello_world':
          $response['$request_id'] = $request_id;
          $response['$options'] = $options;
          $response['script_contents'] =
            '<?xml version="1.0"?>' . 
            "<voip_script name='hello_world'>
              <say><text>Hello, world!</text></say>
              <goto>bye_bye</goto>
            </voip_script>";
          break;
        case 'bye_bye':
          $response['$request_id'] = $request_id;
          $response['$options'] = $options;
          $response['script_contents'] =
            '<?xml version="1.0"?>' . 
            "<voip_script name='bye_bye'>
              <say><text>Nice meeting you.  Goodbye!</text></say>
              <hangup></hangup>
            </voip_script>";
          break;
      }
      break;
  }

  return $response;
}

/*
function voip_test_nodeapi(&$node, $op, $teaser, $page) {
  if ($op == 'view') {
    dsm($node);
  }
}
// */

/* 
function voip_test_form_alter(&$form, &$form_state, $form_id) {
// dsm($form_id);

  if ($form_id == 'node_type_form') {
    dsm($form);
   
    $ops = variable_get('node_options_voip_extension', false);
    dsm($ops);
  }
}
// */
