<?php
/**
 * @file test VOIP hooks.
 */ 

/**
 * Implementation of hook_voip_process_request().
 */
function voip_test_voip_process_request($request_id, $options) {
  $response = NULL;

  switch($request_id) {
    case 'voip_get_script':
      if ($options['script name']  == 'hello world') {
      $response['$request_id'] = $request_id . "\n";
      $response['$options'] = $options;
      $response['result'] = "<voip_script name='hello_world'><action name='say><text>Hello, world!</text></action></voip_script>";
      break;
      }
  }

  return $response;
}

/*
function voip_test_nodeapi(&$node, $op, $teaser, $page) {
  if ($node->type == 'voip_extension' && $op == 'view') {
    dsm($node);
  }
}
// */

/* 
function voip_test_form_alter(&$form, &$form_state, $form_id) {
// dsm($form_id);

  if ($form_id == 'node_type_form') {
    dsm($form);
   
    $ops = variable_get('node_options_voip_extension', false);
    dsm($ops);
  }
}
// */
