<?
/**
 * @file test VOIP hooks.
 */ 

/**
 * Implementation of hook_get_script().
 */
function tester_voip_get_script($script_name, $options) {
  $response = NULL;
  switch($script_name) {
    case 'test_failure':
      $response = FALSE;
      voip_error('(tester.module) test failure, as expected');
      break;
    case 'hello_world':
      $response = "<voip_script name='hello_world'><action name='say><text>Hello, world!</text></action></voip_script>";
      break;
  }

  return $response;
}

/**
 * Implementation of hook_voip_process_request().
 */
function tester_voip_process_request($request_id, $options) {
  $response = NULL;
  switch($request_id) {
    case 'test_failure':
      $response = FALSE;
      voip_error('(tester.module) test failure, as expected');
      break;
    case 'test_echo':
      $response['echo'] = $options;
      break;
  }

  return $response;
}

