<?
/**
 * @file test VOIP hooks.
 */ 

/**
 * Implementation of hook_voip_inbound_validate().
 */
function tester_voip_inbound_validate($request_id, $options) {

  switch($request_id) {
    case 'test':
    case 'echo':
      break;
    case 'invalid':
      $response['status'] = FALSE;
      $response['error_msg'] = 'Invalid option selected';
      break;
  }

  return $response; 
}

/**
 * Implementation of hook_voip_inbound().
 */
function tester_voip_inbound($request_id, $options) {
  switch($request_id) {
    case 'test':
      $response['status'] = FALSE;
      $response['error_msg'] = 'test failure, as expected';
      break;
    case 'echo':
      // never return status == TRUE as in $response['status'] = TRUE;
      $response['echo'] = $options;
      break;
  }

  return $response;
}

